name: nanocrop
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - artic-network::rampart=1.2.0
  - biopython=1.74
  - inotify-tools
  - minimap2=2.17
  - "nodejs>=12"
  - pip
  - "python>=3.7"
  - snakemake-minimal=5.8.1
  - pip:
    - binlorry==1.3.0_alpha1
    - git+https://github.com/artic-network/Porechop.git@v0.3.2pre
    - git+https://github.com/fmfi-compbio/deepnano-blitz.git
